import { ImageBackground, StyleSheet } from 'react-native'

const profileStyles = StyleSheet.create({
    container: {
        backgroundColor : '#F9F9F9',
        width: '100%',
        height: '100%',
        display: 'flex',
        flexDirection: 'column',
    },
    header :{
        fontSize: 30,
        fontWeight: 'bold',
        color: '#FF781F',

    },
    headerContainer :{
        display: "flex", 
        flexDirection: "row", 
        justifyContent: "space-between", 
        margin: "5%",
    },
    signOutButton : {
        backgroundColor : '#FF781F',
        color: 'white',
        padding: 10,
        borderRadius: 15,
        margin: '5%',
        },
    signOutButtonText : {
        color: 'white',
        textAlign: 'center', 
        fontWeight: 'bold',
        fontSize: 20,
    },
    card: {
        display: 'flex',
        position: "relative",
        textAlign: "center",
        flexDirection: 'column',
        height: 300,
        marginVertical: 25,
        marginHorizontal: 25,
        borderRadius: 10,
        backgroundColor: "white",
        shadowColor: "#FF781F",
        shadowOffset: {
            width: 0,
            height: 0,
        },
        shadowOpacity: 5,
        shadowRadius: 2,
    },
    image: {
        width: "100%",
        height: "100%",
        borderRadius: 10,
    },
    cardTextHeader: {
        position: "absolute",
        top: 8,
        backgroundColor: '#266CCF',
        left: 16,
        fontSize: 15,
        fontWeight: "bold",
        color: "white",
        textShadowColor: 'black',
        textShadowOffset: {width: 1, height: 1},
        textShadowRadius: 2,
        width: "90%",

    },
    cardTextBody: {
        position: "absolute",
        bottom: 20,
        left: 16,
        fontSize: 15,
        fontWeight: "bold",
        backgroundColor: '#266CCF',
        color: "white",
        textShadowColor: 'black',
        textShadowOffset: {width: 1, height: 1},
        textShadowRadius: 2,
        width: "80%",
    },
    cardIcon: {
        position: "absolute",
        bottom: 20,
        zIndex: 30,
        left: "90%",
        fontSize: 15,
        fontWeight: "bold",
        color: "white",
        textShadowColor: 'black',
        textShadowOffset: {width: 1, height: 1},
        textShadowRadius: 2,
        width: "100%",
    },
    paginationContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems:'center',
        justifyContent: 'space-around',
        textAlign: 'center',
    },
    paginationButton: {
        color: 'white',
        padding: 10,
        borderRadius: 15,
        widht: '20%',
        margin: '5%',
    },
    paginationButtonText: {
        color: '#FF781F',
        textAlign: 'center', 
        fontWeight: 'bold',
        fontSize: 20,
    },
    paginationText: {
        color: '#FF781F',
        textAlign: 'center', 
        fontWeight: 'bold',
        fontSize: 20,
    },
})

export default profileStyles
